#generated by https://reg2ps.azurewebsites.net/

try {
	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Microsoft\Cryptography\Wintrust\Config   ")){
        return $false 
    };

	if(-NOT (Test-Path -LiteralPath "HKLM:\Software\Wow6432Node\Microsoft\Cryptography\Wintrust\Config ")){ 
        return $false 
    };

	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Microsoft\Cryptography\Wintrust\Config' -Name 'EnableCertPaddingCheck' -ea SilentlyContinue) -eq '1') {
    
    } 
    else { 
        return $false 
    };

	if((Get-ItemPropertyValue -LiteralPath 'HKLM:\Software\Wow6432Node\Microsoft\Cryptography\Wintrust\Config ' -Name 'EnableCertPaddingCheck' -ea SilentlyContinue) -eq '1') {

    }
    else {
        return $false 
    };
}
catch {
     return $false 
}
return $true